 
const data = [
    {
      id: 163321,
      title: 'Essays on Political Economy by Frédéric Bastiat (1801 - 1850)',
      url: 'https://librivox.org/rss/4073',
      originalUrl: 'https://librivox.org/rss/4073',
      link: 'https://librivox.org/essays-on-political-economy-by-frederic-bastiat/',
      description: 'Bastiat asserted that the only purpose of government is to defend the right of an individual to life, liberty, and property. From this definition, Bastiat concluded that the law cannot defend life, liberty and property if it promotes socialist policies inherently opposed to these very things. In this way, he says, the law is perverted and turned against the thing it is supposed to defend. (Introduction by Wikipedia)',
      author: 'LibriVox',
      ownerName: 'LibriVox',
      image: '',
      artwork: '',
      lastUpdateTime: 1622776686,
      lastCrawlTime: 1648485808,
      lastParseTime: 1648485810,
      lastGoodHttpStatusTime: 1648485808,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml; charset=utf-8',
      itunesId: 382955266,
      generator: '',
      language: '',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 0
    },
    {
      id: 96082,
      title: 'Sacred Sons Podcast',
      url: 'https://sacredsons.libsyn.com/sacredsonspodcast',
      originalUrl: 'https://sacredsons.libsyn.com/sacredsonspodcast',
      link: 'http://sacredsonspodcast.libsyn.com/website',
      description: 'Sacred Sons is an organization dedicated to Masculine Alchemy and Embodiment.  We utilize the power of ceremony, ritual, and intentional spaces to deepen into authentic brotherhood and catalyze growth in men worldwide.  Sacred Sons Co-founder Adam Jackson hosts weekly episodes where we dive deep into conversations with facilitators, musicians, athletes, artists, and influencers from around the world.',
      author: 'Adam Jackson, Aubert Bastiat, Jason MacKenzie',
      ownerName: 'Adam Jackson',
      image: 'https://ssl-static.libsyn.com/p/assets/b/b/4/0/bb400bd660fdfd49e5bbc093207a2619/SS_podcast_2022_new.jpg',
      artwork: 'https://ssl-static.libsyn.com/p/assets/b/b/4/0/bb400bd660fdfd49e5bbc093207a2619/SS_podcast_2022_new.jpg',
      lastUpdateTime: 1649472357,
      lastCrawlTime: 1649632722,
      lastParseTime: 1649632725,
      lastGoodHttpStatusTime: 1649632722,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml; charset=utf-8',
      itunesId: 1482881607,
      generator: 'Libsyn WebEngine 2.0',
      language: 'en',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 3100019127
    },
    {
      id: 1527628,
      title: 'Essays on Political Economy by Frederic Bastiat',
      url: 'http://www.loyalbooks.com/book/Political-Economy-Frederic-Bastiat/feed',
      originalUrl: 'http://www.loyalbooks.com/book/Political-Economy-Frederic-Bastiat/feed',
      link: 'http://www.loyalbooks.com/book/Political-Economy-Frederic-Bastiat',
      description: 'Bastiat asserted that the only purpose of government is to defend the right of an individual to life, liberty, and property. From this definition, Bastiat concluded that the law cannot defend life, liberty and property if it promotes socialist policies inherently opposed to these very things. In this way, he says, the law is perverted and turned against the thing it is supposed to defend.',
      author: 'Loyal Books',
      ownerName: 'Loyal Books',
      image: 'http://www.loyalbooks.com/image/feed/Political-Economy-Frederic-Bastiat.jpg',
      artwork: 'http://www.loyalbooks.com/image/feed/Political-Economy-Frederic-Bastiat.jpg',
      lastUpdateTime: 1647738993,
      lastCrawlTime: 1649634291,
      lastParseTime: 1649634293,
      lastGoodHttpStatusTime: 1649634291,
      lastHttpStatus: 200,
      contentType: 'application/xml; charset=UTF-8',
      itunesId: null,
      generator: '',
      language: 'en-us',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 898877651
    },
    {
      id: 1528457,
      title: 'Sophisms of the Protectionists by Frédéric Bastiat',
      url: 'http://www.loyalbooks.com/book/Sophisms-of-the-Protectionists/feed',
      originalUrl: 'http://www.loyalbooks.com/book/Sophisms-of-the-Protectionists/feed',
      link: 'http://www.loyalbooks.com/book/Sophisms-of-the-Protectionists',
      description: '"To rob the public, it is necessary to deceive them," Bastiat said and believed. He reasoned, employing repetition to various applications, against fallacious arguments promoting the "Protection" of industries to the detriment of consumers and society. (Introduction by Katie Riley)',
      author: 'Loyal Books',
      ownerName: 'Loyal Books',
      image: 'http://www.loyalbooks.com/image/feed/Sophisms-of-the-Protectionists.jpg',
      artwork: 'http://www.loyalbooks.com/image/feed/Sophisms-of-the-Protectionists.jpg',
      lastUpdateTime: 1647739252,
      lastCrawlTime: 1649635526,
      lastParseTime: 1649635540,
      lastGoodHttpStatusTime: 1649635526,
      lastHttpStatus: 200,
      contentType: 'application/xml; charset=UTF-8',
      itunesId: null,
      generator: '',
      language: 'en-us',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 1683541669
    },
    {
      id: 2719108,
      title: 'Clube Bastiat',
      url: 'https://feed.megafono.host/clube-bastiat',
      originalUrl: 'https://feed.megafono.host/clube-bastiat',
      link: 'https://www.megafono.host/podcast/clube-bastiat',
      description: 'Este é o podcast oficial do Clube Bastiat.Filosofia, economia e educação, liberal e libertaria.',
      author: 'Clube Bastiat',
      ownerName: 'Clube Bastiat',
      image: 'https://images.megafono.host/channel/artwork/7d95a968-b028-439a-a13e-44cab34fe71e/pp.jpg',
      artwork: 'https://images.megafono.host/channel/artwork/7d95a968-b028-439a-a13e-44cab34fe71e/pp.jpg',
      lastUpdateTime: 1618205740,
      lastCrawlTime: 1649122941,
      lastParseTime: 1649122952,
      lastGoodHttpStatusTime: 1649122941,
      lastHttpStatus: 200,
      contentType: 'application/xml; charset=utf-8',
      itunesId: null,
      generator: 'Megafono Feed v2.0.0',
      language: 'pt-BR',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 3405830081
    },
    {
      id: 2765205,
      title: 'Essays on Political Economy by BASTIAT, Frédéric',
      url: 'https://www.ivoox.com/_fg_f1226582_filtro_1.xml',
      originalUrl: 'https://www.ivoox.com/_fg_f1226582_filtro_1.xml',
      link: 'https://www.ivoox.com/podcast-essays-on-political-economy-by-bastiat-frederic_sq_f1226582_1.html',
      description: 'Bastiat asserted that the only purpose of government is to defend the right of an individual to life, liberty, and property. From this definition, Bastiat concluded that the law cannot defend life, liberty and property if it promotes socialist policies inherently opposed to these very things. In this way, he says, the law is perverted and turned against the thing it is supposed to defend. (Introduction by Wikipedia)',
      author: 'Fantasy Couch',
      ownerName: '',
      image: 'https://static-2.ivoox.com/canales/9/8/9/3/5851470043989_XXL.jpg',
      artwork: 'https://static-2.ivoox.com/canales/9/8/9/3/5851470043989_XXL.jpg',
      lastUpdateTime: 1623239609,
      lastCrawlTime: 1648380460,
      lastParseTime: 1648380471,
      lastGoodHttpStatusTime: 1648380460,
      lastHttpStatus: 200,
      contentType: 'text/xml; charset=utf-8',
      itunesId: null,
      generator: 'iVoox',
      language: 'en',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 545952302
    },
    {
      id: 4706525,
      title: 'Sophisms of the Protectionists',
      url: 'https://s3.amazonaws.com/aplt1rss/4179.rss',
      originalUrl: 'https://s3.amazonaws.com/aplt1rss/4179.rss',
      link: 'https://librivox.org/sophisms-of-the-protectionists-by-frederic-bastiat/',
      description: '"To rob the public, it is necessary to deceive them," Bastiat said and believed. He reasoned, employing repetition to various applications, against fallacious arguments promoting the "Protection" of industries to the detriment of consumers and society. \n' +
        '\n' +
        '(Summary by Katie Riley)',
      author: 'Frédéric Bastiat',
      ownerName: 'Appletfab LLC',
      image: 'http://archive.org/download/LibrivoxCdCoverArt21/sophisms_protectionists_1208.jpg',
      artwork: 'http://archive.org/download/LibrivoxCdCoverArt21/sophisms_protectionists_1208.jpg',
      lastUpdateTime: 1641455899,
      lastCrawlTime: 1648867198,
      lastParseTime: 1641455900,
      lastGoodHttpStatusTime: 1641455894,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml',
      itunesId: null,
      generator: null,
      language: 'en',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 3408456531
    },
    {
      id: 4589201,
      title: 'Essays on Political Economy',
      url: 'https://s3.amazonaws.com/aplt1rss/4073.rss',
      originalUrl: 'https://s3.amazonaws.com/aplt1rss/4073.rss',
      link: 'https://librivox.org/essays-on-political-economy-by-frederic-bastiat/',
      description: 'Bastiat asserted that the only purpose of government is to defend the right of an individual to life, liberty, and property. From this definition, Bastiat concluded that the law cannot defend life, liberty and property if it promotes socialist policies inherently opposed to these very things. In this way, he says, the law is perverted and turned against the thing it is supposed to defend. (Introduction by Wikipedia)',
      author: 'Frédéric Bastiat',
      ownerName: 'Appletfab LLC',
      image: 'http://archive.org/download/LibrivoxCdCoverArt21/essays_political_economy_1208.jpg',
      artwork: 'http://archive.org/download/LibrivoxCdCoverArt21/essays_political_economy_1208.jpg',
      lastUpdateTime: 1639521557,
      lastCrawlTime: 1648835344,
      lastParseTime: 1639521574,
      lastGoodHttpStatusTime: 1639521501,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml',
      itunesId: null,
      generator: null,
      language: 'en',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 3343666285
    },
    {
      id: 1073253,
      title: 'The Law',
      url: 'https://cdn.mises.org/itunes/en_407.xml',
      originalUrl: 'https://cdn.mises.org/itunes/en_407.xml',
      link: '',
      description: 'The Law applies in every way to our own time, which is precisely why so many people credit this one essay for showing them the light of liberty. Narrated by Floy Lilley.',
      author: 'Claude Frédéric Bastiat',
      ownerName: 'Mises Institute',
      image: 'https://cdn.mises.org/TheLaw_300.png',
      artwork: 'https://cdn.mises.org/TheLaw_300.png',
      lastUpdateTime: 1622960344,
      lastCrawlTime: 1649307707,
      lastParseTime: 1648300956,
      lastGoodHttpStatusTime: 1648300951,
      lastHttpStatus: 200,
      contentType: 'application/xml',
      itunesId: 380694913,
      generator: '',
      language: 'en-US',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: null,
      locked: 0,
      imageUrlHash: 2044485895
    },
    {
      id: 841225,
      title: 'Sophisms of the Protectionists by Frédéric Bastiat (1801 - 1850)',
      url: 'https://librivox.org/rss/4179',
      originalUrl: 'https://librivox.org/rss/4179',
      link: 'https://librivox.org/sophisms-of-the-protectionists-by-frederic-bastiat/',
      description: '"To rob the public, it is necessary to deceive them," Bastiat said and believed. He reasoned, employing repetition to various applications, against fallacious arguments promoting the "Protection" of industries to the detriment of consumers and society. (Summary by Katie Riley)',
      author: 'LibriVox',
      ownerName: 'LibriVox',
      image: '',
      artwork: '',
      lastUpdateTime: 1622913359,
      lastCrawlTime: 1649279674,
      lastParseTime: 1649279685,
      lastGoodHttpStatusTime: 1649279674,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml; charset=utf-8',
      itunesId: 383537921,
      generator: '',
      language: '',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 0
    },
    {
      id: 1519326,
      title: 'Law, The by Frédéric Bastiat (1801 - 1850)',
      url: 'https://librivox.org/rss/15134',
      originalUrl: 'https://librivox.org/rss/15134',
      link: 'https://librivox.org/the-law-by-frederic-bastiat/',
      description: '"The law perverted! The law—and, in its wake, all the collective forces of the nation. The law, I say, not only diverted from its proper direction, but made to pursue one entirely contrary! The law becomes the tool of every kind of avarice, instead of being its check! The law guilty of that very inequity which it was its mission to punish! Truly, this is a serious fact, if it exists, and one to which I feel bound to call the attention of my fellow-citizens." —Frédéric Bastiat',
      author: 'LibriVox',
      ownerName: 'LibriVox',
      image: '',
      artwork: '',
      lastUpdateTime: 1623048999,
      lastCrawlTime: 1648330755,
      lastParseTime: 1648330757,
      lastGoodHttpStatusTime: 1648330755,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml; charset=utf-8',
      itunesId: 0,
      generator: '',
      language: '',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 0
    },
    {
      id: 1919174,
      title: 'Capital and Interest by Frédéric Bastiat (1801 - 1850)',
      url: 'https://librivox.org/rss/14246',
      originalUrl: 'https://librivox.org/rss/14246',
      link: 'https://librivox.org/capital-and-interest-by-frederic-bastiat/',
      description: 'Frédéric Bastiat was an early 19th century French economist/statesman whose common sense essays tried to battle the rise of socialist ideology after the French revolution, where provisional governments were rivaling each other for power. Of central concern was who should control the money. How is wealth created? How should it be divided amongst the people? What services should government provide? Same questions we are asking now. This essay addresses the popular fallacy of the day that Capital should be available to all gratuitiously, without necessity of paying back loans, and looking upon any form of interest as Us...',
      author: 'LibriVox',
      ownerName: 'LibriVox',
      image: '',
      artwork: '',
      lastUpdateTime: 1623112326,
      lastCrawlTime: 1648347795,
      lastParseTime: 1648347799,
      lastGoodHttpStatusTime: 1648347795,
      lastHttpStatus: 200,
      contentType: 'application/rss+xml; charset=utf-8',
      itunesId: null,
      generator: '',
      language: '',
      type: 0,
      dead: 0,
      crawlErrors: 0,
      parseErrors: 0,
      categories: [Object],
      locked: 0,
      imageUrlHash: 0
    }
  ]
export {data}